### ISSUE TITLE
Create guide on creating Web App in README.md

### ISSUE THREAD

**Issue by jared-maki** [cse-uprc/room-availability#1]
@Jacob-Hunt , whenever you have time would you be able to write a quick guide on how to set up the web application? Thanks!

**Comment by Jacob-Hunt** [comment]
@jemaki56 It might be a couple weeks until I can get to it, as I got behind on homework to do the hackathon and need to catch up right now. But yes, I can definitely do that!

**Comment by jared-maki** [comment]
@Jacob-Hunt Awesome! No rush at all.

**Comment by Jacob-Hunt** [comment]
Alright! Guide has been posted!
